spring:
  application:
    name: MALL-GATEWAY
  cloud:
    nacos:
      server-addr: 10.15.0.4:8848
    gateway:
      routes:
        - id: product_router
          uri: lb://MALL-PRODUCT
          predicates:
            - Path= /api/product/**
          filters:
            - RewritePath= /api/?(?<segment>.*),/$\{segment}
        - id: third_party
          uri: lb://MALL-THIRDPARTY
          predicates:
            - Path= /api/thirdparty/**
          filters:
            - RewritePath= /api/thirdparty/?(?<segment>.*),/$\{segment}
        - id: admin_router
          uri: lb://MALL-ADMIN
          predicates:
            - Path= /api/**
          filters:
            - RewritePath= /api/?(?<segment>.*),/renren-fast/$\{segment}




server:
  port: 88
log:
  request:
    enable: false