spring:
  application:
    name: MALL-GATEWAY
  cloud:
    nacos:
      server-addr: 10.15.0.4:8848
    gateway:
      routes:
        - id: product_router
          uri: lb://MALL-PRODUCT
          predicates:
            - Path= /api/product/**
          filters:
            - RewritePath= /api/?(?<segment>.*),/$\{segment}
        - id: member_router
          uri: lb://MALL-MEMBER
          predicates:
            - Path= /api/member/**
          filters:
            - RewritePath= /api/?(?<segment>.*),/$\{segment}
        - id: ware_router
          uri: lb://MALL-WARE
          predicates:
            - Path= /api/ware/**
          filters:
            - RewritePath= /api/?(?<segment>.*),/$\{segment}
        - id: third_party
          uri: lb://MALL-THIRDPARTY
          predicates:
            - Path= /api/thirdparty/**
          filters:
            - RewritePath= /api/thirdparty/?(?<segment>.*),/$\{segment}
        - id: admin_router
          uri: lb://MALL-ADMIN
          predicates:
            - Path= /api/**
          filters:
            - RewritePath= /api/?(?<segment>.*),/renren-fast/$\{segment}
        - id: mall_host_product
          uri: lb://MALL-PRODUCT
          predicates:
            - Host=mall.com,item.mall.com
        - id: mall_host_search
          uri: lb://MALL-SEARCH
          predicates:
            - Host=search.mall.com
        - id: mall_host_auth
          uri: lb://MALL-AUTH
          predicates:
            - Host=auth.mall.com
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss




server:
  port: 88
log:
  request:
    enable: false